services:

  postgres:
    image: postgres:15
    container_name: algosphere_postgres
    restart: always
    environment:
      POSTGRES_USER: algosphere
      POSTGRES_PASSWORD: strongpassword
      POSTGRES_DB: algosphere_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: algosphere_backend
    depends_on:
      - postgres
      - ide-api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://algosphere:strongpassword@postgres:5432/algosphere_db
      IDE_API_URL: http://ide-api:4000

  ide-api:
    build: ./ide-services/api-server
    container_name: marevlo_ide_api
    ports:
      - "4000:4000"

  runner:
    build: ./ide-services/runner
    container_name: marevlo_runner
    ports:
      - "4002:4002"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  jupyter:
    image: jupyter/minimal-notebook
    container_name: marevlo_jupyter
    ports:
      - "8888:8888"
    environment:
      JUPYTER_TOKEN: ""
    command:
      - "start-notebook.sh"
      - "--NotebookApp.token="
      - "--NotebookApp.password="
      - "--NotebookApp.allow_origin=*"
      - "--NotebookApp.disable_check_xsrf=True"

  redis:
    image: redis:7
    container_name: marevlo_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
