"""add discussion tables and relationships

Revision ID: b02eae1558dc
Revises: 6395c5c5c4d7
Create Date: 2026-05-16 10:39:46.990810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b02eae1558dc'
down_revision: Union[str, None] = '6395c5c5c4d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('mira_appeal_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_mira_appeal_pending', table_name='mira_appeal_queue', postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('mira_concept_lattices', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_mira_episodic_user_time', table_name='mira_episodic')
    op.alter_column('mira_gate_status', 'attempt_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('idx_mira_grading_user', table_name='mira_grading_events')
    op.alter_column('mira_review_queue', 'interval_days',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_review_queue', 'ease_factor',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_review_queue', 'consecutive_passes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_rubrics', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_rubrics', 'human_reviewed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_semantic_memory', 'projects_in_progress',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('mira_semantic_memory', 'preferred_styles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('mira_semantic_memory', 'total_concepts_mastered',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('mira_semantic_memory', 'total_concepts_touched',
               existing_type=sa.INTEGER(),
               server_default=None,
               nullable=False)
    op.alter_column('mira_semantic_memory', 'common_misconceptions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               nullable=False)
    op.alter_column('mira_user_profiles', 'tier',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'quota_used_this_period',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'beliefs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'bandit_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'personal_prompt',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'frustration_signals',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=None,
               existing_nullable=False)
    op.alter_column('problems', 'time_limit_s',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=None,
               existing_nullable=True)
    op.alter_column('problems', 'memory_limit_mb',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=True)
    # op.drop_index('idx_problems_topic', table_name='problems')
    op.execute("DROP INDEX IF EXISTS idx_problems_topic")
    # op.drop_column('problems', 'topic')
    op.execute("ALTER TABLE problems DROP COLUMN IF EXISTS topic")
    # op.drop_index('idx_user_profiles_xp', table_name='user_profiles')
    op.execute("DROP INDEX IF EXISTS idx_user_profiles_xp")
    # op.drop_column('user_profiles', 'college_year')
    op.execute("ALTER TABLE user_profiles DROP COLUMN IF EXISTS college_year")
    # op.drop_column('user_profiles', 'dob')
    op.execute("ALTER TABLE user_profiles DROP COLUMN IF EXISTS dob")
    # op.drop_column('user_profiles', 'problems_solved')
    op.execute("ALTER TABLE user_profiles DROP COLUMN IF EXISTS problems_solved")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('problems_solved', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('user_profiles', sa.Column('dob', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('user_profiles', sa.Column('college_year', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.create_index('idx_user_profiles_xp', 'user_profiles', [sa.text('xp DESC')], unique=False)
    op.add_column('problems', sa.Column('topic', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.create_index('idx_problems_topic', 'problems', ['topic'], unique=False)
    op.alter_column('problems', 'memory_limit_mb',
               existing_type=sa.INTEGER(),
               server_default=sa.text('256'),
               existing_nullable=True)
    op.alter_column('problems', 'time_limit_s',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               server_default=sa.text("'2'::double precision"),
               existing_nullable=True)
    op.alter_column('mira_user_profiles', 'preferences',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'onboarding_completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'frustration_signals',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'personal_prompt',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'bandit_state',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'beliefs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'{}'::jsonb"),
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'quota_used_this_period',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('mira_user_profiles', 'tier',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'free'::character varying"),
               existing_nullable=False)
    op.alter_column('mira_semantic_memory', 'common_misconceptions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               nullable=True)
    op.alter_column('mira_semantic_memory', 'total_concepts_touched',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('mira_semantic_memory', 'total_concepts_mastered',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               nullable=True)
    op.alter_column('mira_semantic_memory', 'preferred_styles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               nullable=True)
    op.alter_column('mira_semantic_memory', 'projects_in_progress',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               server_default=sa.text("'[]'::jsonb"),
               nullable=True)
    op.alter_column('mira_rubrics', 'human_reviewed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('mira_rubrics', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('mira_review_queue', 'consecutive_passes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('mira_review_queue', 'ease_factor',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               server_default=sa.text('2.5'),
               existing_nullable=False)
    op.alter_column('mira_review_queue', 'interval_days',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.create_index('idx_mira_grading_user', 'mira_grading_events', ['user_id', sa.text('created_at DESC')], unique=False)
    op.alter_column('mira_gate_status', 'attempt_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.create_index('idx_mira_episodic_user_time', 'mira_episodic', ['user_id', sa.text('created_at DESC')], unique=False)
    op.alter_column('mira_concept_lattices', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.create_index('idx_mira_appeal_pending', 'mira_appeal_queue', ['status'], unique=False, postgresql_where="((status)::text = 'pending'::text)")
    op.alter_column('mira_appeal_queue', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    # ### end Alembic commands ###
